language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '10'
  - '8'
after_success:
  - npm run travis-deploy-once "npm run semantic-release && npm run report-coverage && npm run docs && npm run deploy-docs"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
